### PR TITLE
transferPropsTo() is being deprecated

### PR DESCRIPTION
**Pull request by LeezQ**
transferPropsTo transferPropsTo() is being deprecated , change to  ...this.props

### CODE REVIEW

**Comment by MandarinConLaBarba** [comment]
In what version did the spread operator get introduced? The package.json calls for `>=0.10.0` - I'm thinking if we add the spread operator, we need to go up to 11 or 12?

**Comment by LeezQ** [comment]
you can up to 12 , because 12 is the stable version now.

**Comment by n0m0r3pa1n** [comment]
May be you didn't update the npm package ?

**Comment by thehuey** [comment]
:+1:

**Pull request closed without merging**
